"""004_client_management

Revision ID: 1b4b4e788c8b
Revises: e03fcb5e46a4
Create Date: 2026-05-19 07:44:15.616737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b4b4e788c8b'
down_revision: Union[str, Sequence[str], None] = 'e03fcb5e46a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('counselor_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['counselor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_client_invites_counselor_id'), 'client_invites', ['counselor_id'], unique=False)
    op.create_index(op.f('ix_client_invites_token'), 'client_invites', ['token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_client_invites_token'), table_name='client_invites')
    op.drop_index(op.f('ix_client_invites_counselor_id'), table_name='client_invites')
    op.drop_table('client_invites')
    # ### end Alembic commands ###
