"""007_ai_records

Revision ID: 1c9166897b31
Revises: a3f1b9c40e5d
Create Date: 2026-05-20 14:54:59.867497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c9166897b31'
down_revision: Union[str, Sequence[str], None] = 'a3f1b9c40e5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_chat_messages_room_created'), table_name='chat_messages')
    op.add_column('session_records', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('session_records', sa.Column('audio_s3_key', sa.String(length=500), nullable=True))
    op.add_column('session_records', sa.Column('recording_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('session_records', sa.Column('recording_ended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session_records', 'recording_ended_at')
    op.drop_column('session_records', 'recording_started_at')
    op.drop_column('session_records', 'audio_s3_key')
    op.drop_column('session_records', 'status')
    op.create_index(op.f('ix_chat_messages_room_created'), 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.drop_table('audio_chunks')
    # ### end Alembic commands ###
