"""add updated_at to qualifications and careers

Revision ID: 30c1bfbc724f
Revises: d74027f66e1c
Create Date: 2026-05-27 13:44:44.691654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '30c1bfbc724f'
down_revision: Union[str, Sequence[str], None] = 'd74027f66e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_room_participants',
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('room_id', 'user_id')
    )
    op.add_column('careers', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('careers', 'role',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=True)
    op.alter_column('careers', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_index(op.f('ix_chat_messages_room_created'), table_name='chat_messages')
    op.add_column('chat_rooms', sa.Column('room_type', sa.String(length=20), nullable=False))
    op.add_column('chat_rooms', sa.Column('host_id', sa.UUID(), nullable=True))
    op.add_column('chat_rooms', sa.Column('name', sa.String(length=120), nullable=True))
    op.alter_column('chat_rooms', 'session_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_foreign_key(None, 'chat_rooms', 'users', ['host_id'], ['id'])
    op.add_column('qualifications', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('session_participants', sa.Column('is_waitlisted', sa.Boolean(), nullable=False))
    op.add_column('session_participants', sa.Column('waitlist_position', sa.Integer(), nullable=True))
    op.add_column('session_records', sa.Column('status', sa.String(length=20), nullable=False))
    op.add_column('session_records', sa.Column('audio_s3_key', sa.String(length=500), nullable=True))
    op.add_column('session_records', sa.Column('recording_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('session_records', sa.Column('recording_ended_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('status', sa.String(length=20), server_default='active', nullable=False))
    op.add_column('users', sa.Column('notification_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('auth_provider', sa.String(length=20), server_default='email', nullable=False))
    op.add_column('verification_audits', sa.Column('target_type', sa.String(length=30), nullable=True))
    op.add_column('verification_audits', sa.Column('target_id', sa.UUID(), nullable=True))
    op.alter_column('verification_audits', 'credential_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('verification_audits', 'action',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('verification_audits', 'action',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.alter_column('verification_audits', 'credential_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('verification_audits', 'target_id')
    op.drop_column('verification_audits', 'target_type')
    op.drop_column('users', 'auth_provider')
    op.drop_column('users', 'notification_preferences')
    op.drop_column('users', 'status')
    op.drop_column('session_records', 'recording_ended_at')
    op.drop_column('session_records', 'recording_started_at')
    op.drop_column('session_records', 'audio_s3_key')
    op.drop_column('session_records', 'status')
    op.drop_column('session_participants', 'waitlist_position')
    op.drop_column('session_participants', 'is_waitlisted')
    op.drop_column('qualifications', 'updated_at')
    op.drop_constraint(None, 'chat_rooms', type_='foreignkey')
    op.alter_column('chat_rooms', 'session_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('chat_rooms', 'name')
    op.drop_column('chat_rooms', 'host_id')
    op.drop_column('chat_rooms', 'room_type')
    op.create_index(op.f('ix_chat_messages_room_created'), 'chat_messages', ['room_id', 'created_at'], unique=False)
    op.alter_column('careers', 'is_current',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('careers', 'role',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=True)
    op.drop_column('careers', 'updated_at')
    op.drop_table('chat_room_participants')
    # ### end Alembic commands ###
